### ISSUE TITLE
Parse return message from vici

### ISSUE THREAD

**Issue by pepijndeboever** [driesmp/dynamicprefixvici#5]
Currently the return message from vici is not prossesed, so it is unsure whether or not the address pool is succesfully updated.

**Comment by driesmp** [comment]
[output.txt](https://github.com/driesmp/dynamicprefixvici/files/10271099/output.txt)

**Comment by driesmp** [comment]
/**
 * Vici parse result, as returned by vici_parse().
 */
typedef enum {
	/** encountered a section start, has a name */
	VICI_PARSE_BEGIN_SECTION,
	/** encountered a section end */
	VICI_PARSE_END_SECTION,
	/** encountered a list start, has a name */
	VICI_PARSE_BEGIN_LIST,
	/** encountered a list element, has a value */
	VICI_PARSE_LIST_ITEM,
	/** encountered a list end */
	VICI_PARSE_END_LIST,
	/** encountered a key/value pair, has a name and a value */
	VICI_PARSE_KEY_VALUE,
	/** encountered valid end of message */
	VICI_PARSE_END,
	/** parse error */
	VICI_PARSE_ERROR,
} vici_parse_t;

**Comment by driesmp** [comment]
[tmp.0.VZxCHU.txt](https://github.com/driesmp/dynamicprefixvici/files/10816905/tmp.0.VZxCHU.txt)

**Comment by driesmp** [comment]
Dat valt mee om te parsen é :-)

**Comment by driesmp** [comment]
"received message: yes" on the terminal, so works great

Should we error out when "Received message: no"?
Does it have value in being printed instead of exiting with 1 as error code?
